export const USER_INFORMATION = "USER_INFORMATION"
export const USER_INFORMATION_SUCCESS = "USER_INFORMATION_SUCCESS"
export const USER_INFORMATION_ERROR = "USER_INFORMATION_ERROR"
export const GET_PART_USER = "GET_PART_USER"

export const DELETE_USER_POST = "DELETE_USER_POST"; 

export const UPDATE_USER_POST = "UPDATE_USER_POST";

export const ADD_USER_POST = "ADD_USER_POST";